### ISSUE TITLE
Package Install Error

### ISSUE THREAD

**Issue by sidu21** [nmhaddad/Fast-Track#9]
**Command:** pip install .
**Error:**
Processing /home/user/Fast-Track
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      error: Multiple top-level packages discovered in a flat-layout: ['media', 'models', 'config', 'fast_track'].
      
      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.
      
      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:
      
      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names
      
      To find more information, look for "package discovery" on setuptools docs.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Fix:** (atleast it worked for me)
Added the following lines in pyproject.toml file at the end.
```
[tool.setuptools]
py-modules = []
```

**Comment by nmhaddad** [comment]
@sidu21, thanks for pointing this out. I've added your fix in #10.
